---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.initModels.image }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.hooks.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- if not .Values.chartdebug }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- end }}
    {{- end }}
spec:
  template:
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
        - echo "Copying models.";
          cp -r /root/models /root/models-storage/;
          chown -R 1000:1000 /root/models-storage;
          echo "Copied models for video PVCs.";
        image: {{ .Values.repository }}/{{ .Values.initModels.image }}:{{ .Chart.AppVersion }}
        name: {{ .Release.Name }}-{{ .Values.initModels.image }}-container
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/models-storage/models
          name: models-storage
          subPath: models
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-models-pvc
  backoffLimit: 3
