---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-sample-data
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.hooks.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- if not .Values.chartdebug }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- end }}
    {{- end }}
spec:
  template:
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
        - echo "Copying sample data, tracker-config.json, videos.";
          cp -r /root/sample_data /root/sample-data-storage/;
          chown -R 1000:1000 /root/sample-data-storage;
          echo "Copied sample_data folder.";
          cp -r /root/controller/config/tracker-config.json /root/controller-storage/tracker-config.json;
          chown -R 1000:1000 /root/controller-storage;
          echo "Copied tracker-config.json file.";
          cp -r /root/videos/* /root/videos-storage/;
          chown -R 1000:1000 /root/videos;
          echo "Copied videos folder.";
        image: {{ .Values.repository }}/{{ .Values.initModels.image }}:{{ .Chart.AppVersion }}
        name: {{ .Release.Name }}-{{ .Values.initModels.image }}-container
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/sample-data-storage/sample_data
          name: sample-data-storage
          subPath: sample_data
        - mountPath: /root/controller-storage/
          name: controller-storage
        - mountPath: /root/videos-storage
          name: videos-storage
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: sample-data-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-sample-data-pvc
      - name: controller-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-controller-pvc
      - name: videos-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-videos-pvc
  backoffLimit: 3
