apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scene-dep
  labels:
    app: {{ .Release.Name }}-scene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-scene
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-scene
    spec:
      shareProcessNamespace: true
      initContainers:
      - name: wait-for-web-initcontainer
        image: busybox
        command: ["/bin/sh", "-c", "until wget -q --spider http://web.{{ .Release.Namespace }}; do sleep 1; done"]
      containers:
        - args:
          - controller
          - --broker
          - broker.{{ .Release.Namespace }}
          - --resturl
          - https://web.{{ .Release.Namespace }}/api/v1
          - --ntp
          - ntpserv.{{ .Release.Namespace }}
          image: {{ .Values.repository }}/{{ .Values.scene.image }}:{{ .Chart.AppVersion }}
          name: {{ .Release.Name }}-scene
          env:
          - name: VDMS_HOSTNAME
            value: vdms.{{ .Release.Namespace }}
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 1
          resources: {}
          volumeMounts:
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
          - mountPath: /run/secrets/django
            name: django
            readOnly: true
          - mountPath: /run/secrets/controller.auth
            name: controller-auth
            readOnly: true
            subPath: controller.auth
          - mountPath: /home/scenescape/SceneScape/media
            name: media-storage
          - mountPath: /home/scenescape/SceneScape/tracker-config.json
            name: controller-storage
            subPath: tracker-config.json
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-certs
      - name: django
        secret:
          secretName: {{ .Release.Name }}-django
      - name: controller-auth
        secret:
          secretName: {{ .Release.Name }}-controller.auth
      - name: media-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-media-pvc
      - name: controller-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-controller-pvc
status: {}
