{{- if .Values.sources.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scenescape-sources
  labels:
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.hooks.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- end }}
spec:
  template:
    spec:
      containers:
      - command: ["ls"]
        image: {{ .Values.repository }}/scenescape-sources:{{ .Chart.AppVersion }}
        name: scenescape-sources-container
        imagePullPolicy: Always
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end}}
