{{- if .Values.tests.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.tests.image }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.hooks.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- if not .Values.chartdebug }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- end }}
    {{- end }}
spec:
  template:
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
        - echo "Copying models.";
          cp -r /root/tests /root/tests-storage/;
          chown -R 1000:1000 /root/tests-storage;
          echo "Copied tests folder.";
        image: {{ .Values.repository }}/{{ .Values.tests.image }}:{{ .Chart.AppVersion }}
        name: {{ .Release.Name }}-{{ .Values.tests.image }}-container
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/tests-storage/tests
          name: tests-storage
          subPath: tests
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tests-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-tests-pvc
  backoffLimit: 3
{{- end }}
