{{- if .Values.vdms.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vdms-dep
  labels:
    app: {{ .Release.Name }}-vdms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vdms
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vdms
    spec:
      shareProcessNamespace: true
      containers:
        - image: intellabs/vdms:latest
          name: {{ .Release.Name }}-vdms
          env:
          - name: OVERRIDE_ca_file
            value: /run/secrets/certs/scenescape-ca.pem
          - name: OVERRIDE_cert_file
            value: /run/secrets/certs/scenescape-vdms-s.crt
          - name: OVERRIDE_key_file
            value: /run/secrets/certs/scenescape-vdms-s.key
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: certs
        secret:
          secretName: {{ .Release.Name }}-certs
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vdms
spec:
  selector:
    app: {{ .Release.Name }}-vdms
  ports:
  - name: "55555"
    protocol: TCP
    port: 55555
    targetPort: 55555
{{- end }}
